/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ModelController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import model.BrowserTransferHandler;
import model.ModelCollection;

import model.*;
import util.*;

/**
 *
 * @author vmikovsk
 */
public class Browser extends javax.swing.JInternalFrame implements TreeSelectionListener, Observer {
    
    private ModelController modelController = null;
    
    /**
     * Creates new form Browser
     */
    public Browser() {
        initComponents();
       
        populateTree();       
        
        //tree.setDragEnabled(true);
        //tree.setTransferHandler(new TreeNodeTransferHandler());
        
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
        tree.addTreeSelectionListener(this);
        
        //Register ourselve as an observer to ModelCollection.
        ModelCollection.getInstance().addObserver(this);
    }
    
    @Override
    public void valueChanged(TreeSelectionEvent e) {
        //Returns the last path element of the selection.
        //This method is useful only when the selection model allows a single selection.
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) tree.getLastSelectedPathComponent();

        if (node == null)
            //Nothing is selected.
            return;

        modelController.setCurrentSelectedNode(node);

    }
    
    public void setModelController(ModelController modelController) {
        this.modelController = modelController;
    }
    
    public javax.swing.JTree getTree() {
        return tree;
    }
    
    private void populateTree(){
        tree.setRootVisible(false);        
        tree.setModel(ModelCollection.getInstance());
        
        tree.setTransferHandler(new BrowserTransferHandler());
        tree.setCellRenderer(new BrowserTreeCellRenderer());
        
        //Create a default model.
        DefaultMutableTreeNode firstLeaf = ((DefaultMutableTreeNode)tree.getModel().getRoot()).getFirstLeaf();
        tree.setSelectionPath(new TreePath(firstLeaf.getPath()));       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        newModelButton = new javax.swing.JMenu();
        newPackageButton = new javax.swing.JMenu();
        newClassButton = new javax.swing.JMenu();
        deleteButton = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Model browser");

        jPanel1.setName(""); // NOI18N

        tree.setDragEnabled(true);
        tree.setDropMode(javax.swing.DropMode.ON_OR_INSERT);
        tree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jMenuBar1.setName(""); // NOI18N

        newModelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NewModelIcon.png"))); // NOI18N
        newModelButton.setToolTipText("New model");
        newModelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newModelButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(newModelButton);

        newPackageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NewPackageIcon.png"))); // NOI18N
        newPackageButton.setText("Add Package");
        newPackageButton.setPreferredSize(new java.awt.Dimension(41, 32));
        newPackageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPackageButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(newPackageButton);

        newClassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NewNamespaceIcon.png"))); // NOI18N
        newClassButton.setToolTipText("New Class");
        newClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newClassButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(newClassButton);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DeleteElementIcon.png"))); // NOI18N
        deleteButton.setToolTipText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(deleteButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newModelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newModelButtonMouseClicked
        //show name window
        String s = (String)JOptionPane.showInputDialog(
                            this,
                            "Enter model name:",
                            "Model name",
                            JOptionPane.PLAIN_MESSAGE,
                            null,
                            null,
                            "Model1");
        if ((s != null) && (s.length() > 0)) {
            modelController.addNewModel(s);
            tree.repaint();
        }
        else{
            JOptionPane.showMessageDialog(this,
                "Illegal name entered",
                "Illegal name",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_newModelButtonMouseClicked

    private void newClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newClassButtonMouseClicked
       createNewClass();
    }//GEN-LAST:event_newClassButtonMouseClicked

    public void createNewClass() {
        if (modelController == null) {
            Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, "There is no modelController.");
            return;
        }
            
        //show name window
        String s = "Class1";
        try{
            //find selected element node
            TreePath selectedPath = tree.getSelectionPath();
            
            model.Class classElement;
            classElement = modelController.addNewClass(s);
            tree.setSelectionPath(selectedPath);
            
            //Call to ClassElementDialog.
            ClassElementDialog jd = new ClassElementDialog(null, closable, classElement, modelController); //TODO: reference to modelController?
            jd.setVisible(true);
            ModelCollection.getInstance().reload();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
            "A parent node must be selected",
            "Model Exception",
            JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, e);
        }       
    }
    
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        TreePath selectedPath = tree.getSelectionPath();
        if ( selectedPath != null ){

            MutableTreeNode selectedNode = (MutableTreeNode) selectedPath.getLastPathComponent();
            //show name window
            int response = JOptionPane.showConfirmDialog(this, 
                                "You are going to delete node "+selectedNode.toString(), 
                                "Delete confirmation", 
                                JOptionPane.OK_CANCEL_OPTION);
            if ( response != 0 ){ // user Cancels
                return;
            }
            try {
                if(selectedNode instanceof Model){
                    Model modelNode = (Model) selectedNode;
                    modelController.removeModel(modelNode);
                }
                else if(selectedNode instanceof NamedElement){
                    NamedElement namedElement = (NamedElement) selectedNode;
                    modelController.removeElement(namedElement);
                }
                
                ModelCollection.getInstance().reload();
                //create new object
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Model Exception",
                JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void treeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treeMouseClicked
        if (evt.getClickCount() >= 2) {
            TreePath selectedPath = tree.getSelectionPath();
            if(selectedPath != null){
                MutableTreeNode selectedNode = (MutableTreeNode) selectedPath.getLastPathComponent();
                if(selectedNode instanceof NamedElement) {
                    if (selectedNode instanceof Property) {
                        PropertyElementDialog jd = new PropertyElementDialog(null, closable, (Property)selectedNode, modelController);
                        jd.setVisible(true);
                        //TODO dialog asigned to an element
                        ModelCollection.getInstance().reload();
                    } else if (selectedNode instanceof model.Class) {                      
                        ClassElementDialog jd = new ClassElementDialog(null, closable, (model.Class)selectedNode, modelController);
                        jd.setVisible(true);
                        //TODO dialog asigned to an element                       
                        ModelCollection.getInstance().reload();
                    } else if (selectedNode instanceof model.Package) {                     
                        PackageElementDialog jd = new PackageElementDialog(null, closable, (model.Package)selectedNode, modelController);
                        jd.setVisible(true);
                        //TODO dialog asigned to an element                       
                        ModelCollection.getInstance().reload();      
                    }
                }
                else if(selectedNode instanceof Model){
                    //show properties window
                    ModelDialog jd = new ModelDialog(null, closable, (Model)selectedNode);
                    jd.setVisible(true);
                    //TODO dialog asigned to an element
                    ModelCollection.getInstance().reload();
                }
            }
        }
    }//GEN-LAST:event_treeMouseClicked

    private void newPackageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPackageButtonMouseClicked
        createNewPackage();
    }//GEN-LAST:event_newPackageButtonMouseClicked

    
    public void createNewPackage() {
        if (modelController == null) {
            Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, "There is no modelController.");
            return;
        }
            
        //show name window
        String s = "Package1";
        try{
            //find selected element node
            TreePath selectedPath = tree.getSelectionPath();

            model.Package packageElement;
            packageElement = modelController.addNewPackage(s);
            
            tree.setSelectionPath(selectedPath);
            
            //Call to PackageElementDialog.
            PackageElementDialog jd = new PackageElementDialog(null, closable, packageElement, modelController); //TODO: reference to modelController?
            jd.setVisible(true);
            ModelCollection.getInstance().reload();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,
            "A parent node must be selected",
            "Model Exception",
            JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Browser.class.getName()).log(Level.SEVERE, null, e);
        }       
    }    
    
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Browser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Browser().setVisible(true);
            }
        });
    }

    //private ClassDialogBox classDialogBox;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu newClassButton;
    private javax.swing.JMenu newModelButton;
    private javax.swing.JMenu newPackageButton;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Object deletedObject) {
        TreePath selectedPath = tree.getSelectionPath();
        ModelCollection.getInstance().reload();
        tree.repaint();
        tree.setSelectionPath(selectedPath);
    }
}
