/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ModelController;
import view.diagramPane.DiagramPane;

/**
 *
 * @author vmikovsk
 */
public class MetaArchitect extends javax.swing.JFrame {

    private final ModelController modelController = new ModelController();
    private Browser browser;
    private Toolbox toolbox;  
    private DiagramPane diagramPane;
    
    /**
     * Creates new form browser
     */
    public MetaArchitect() {
        initComponents();
        initBrowser();
    }  
    
    private void initBrowser(){      
        browser = new view.Browser();
        browser.setVisible(true);
        browser.setModelController(modelController);
        desktopPane.add(browser);
        desktopPane.getDesktopManager().activateFrame(browser);
                
        toolbox = new view.Toolbox();
        toolbox.setVisible(true);
        desktopPane.add(toolbox);
        desktopPane.getDesktopManager().activateFrame(toolbox);       
        
        diagramPane = new view.diagramPane.DiagramPane(modelController);
        diagramPane.setVisible(true);
        desktopPane.add(diagramPane);
        desktopPane.getDesktopManager().activateFrame(diagramPane);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        browserViewButton = new javax.swing.JMenuItem();
        toolboxViewButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        browserViewButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        browserViewButton.setText("Browser");
        browserViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserViewButtonActionPerformed(evt);
            }
        });
        jMenu3.add(browserViewButton);

        toolboxViewButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        toolboxViewButton.setText("Toolbox");
        toolboxViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolboxViewButtonActionPerformed(evt);
            }
        });
        jMenu3.add(toolboxViewButton);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browserViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserViewButtonActionPerformed
        browser.show();
    }//GEN-LAST:event_browserViewButtonActionPerformed

    private void toolboxViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolboxViewButtonActionPerformed
        toolbox.show();
    }//GEN-LAST:event_toolboxViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MetaArchitect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MetaArchitect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MetaArchitect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MetaArchitect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MetaArchitect a = new MetaArchitect();
//                a.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
                a.setVisible(true);
            }
        });
    }

    //private ClassDialogBox classDialogBox;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem browserViewButton;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem toolboxViewButton;
    // End of variables declaration//GEN-END:variables
}
