/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.diagramPane;

import controller.ModelController;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.Point;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DragGestureEvent;
import java.awt.dnd.DragGestureListener;
import java.awt.dnd.DragGestureRecognizer;
import java.awt.dnd.DragSource;
import java.awt.dnd.DragSourceDragEvent;
import java.awt.dnd.DragSourceDropEvent;
import java.awt.dnd.DragSourceEvent;
import java.awt.dnd.DragSourceListener;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetAdapter;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreePath;
import model.NamedElement;
import view.MetaArchitect;
import view.MetaArchitect;

/**
 *
 * @author rzon
 */
public class DiagramPane extends javax.swing.JInternalFrame {

    private MetaArchitect metaArchitect;
    public PanelDiagramPane drawPanel;   
    
    private ModelController modelController = null;
    
    /**
     * Creates new form DiagramPane
     */
    public DiagramPane(MetaArchitect ma, ModelController modelController) {
        initComponents();
        this.metaArchitect = ma;
        
        try {
            drawPanel = new PanelDiagramPane(this.getBounds(), metaArchitect, modelController);
            getContentPane().add(drawPanel);

            pack();
            setVisible(true);
            
            ma.toolbox.getTree().setDragEnabled(true);
            ma.toolbox.getTree().setTransferHandler(new TreeTransferHandler());
            
            this.setTransferHandler(new InternalFrameTransferHandler(metaArchitect));
            
            //ma.browser.getTree().setDragEnabled(true);
            //ma.browser.getTree().setTransferHandler(new TreeTransferHandler());
         
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(DiagramPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Class diagram");
        setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
