/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.diagramPane;

import controller.ModelController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rzon
 */
public class DiagramPane extends javax.swing.JInternalFrame {

    public PanelDiagramPane drawPanel;          
    
    /**
     * Creates new form DiagramPane
     */
    public DiagramPane(ModelController modelController) {
        initComponents();
        
        try {
            drawPanel = new PanelDiagramPane(this.getBounds(), modelController);
            getContentPane().add(drawPanel);

            pack();
            setVisible(true);           
            
            this.setTransferHandler(new InternalFrameTransferHandler(modelController));
            
            //ma.browser.getTree().setDragEnabled(true);
            //ma.browser.getTree().setTransferHandler(new TreeTransferHandler());
         
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(DiagramPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Class diagram");
        setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1242, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
