/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.diagramPane;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JTextField;
import model.NamedElement;

/**
 *
 * @author rzon
 */
public class PanelDiagramPane extends javax.swing.JPanel {

    private ArrayList<UIElement> drawableElements = new ArrayList<UIElement>();
       
    /**
     * Creates new form PanelDiagramPane
     */
    public PanelDiagramPane(Rectangle r) throws IOException {
        initComponents();
        this.setPreferredSize(new Dimension(1000, 1000));
        Rectangle r2 = new Rectangle(new Dimension(1000, 1000));
        this.setBounds(r2);
    }
    
    //private static final int PREF_W = 200;
   // private static final int PREF_H = PREF_W;

   /* @Override
    public Dimension getPreferredSize() {
       return new Dimension(PREF_W, PREF_H);
    }*/

    @Override
    protected void paintComponent(Graphics g) {
       super.paintComponent(g);

       for (int i = 0; i < drawableElements.size(); i++) {
           UIElement e = drawableElements.get(i);
           e.draw(g);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    void setNewPackage(NamedElement ne, Point dropPoint) {
        PackageUIElement e = new PackageUIElement();
        e.element = ne;
        e.x = dropPoint.x;
        e.y = dropPoint.y;
        drawableElements.add(e);
        repaint();
    }

    void setNewClass(NamedElement ne, Point dropPoint) {
        ClassUIElement e = new ClassUIElement();
        e.element = ne;
        e.x = dropPoint.x;
        e.y = dropPoint.y;
        drawableElements.add(e);
        repaint();
    }
}
